export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';
export const FETCH_WEATHER_FAILED = 'FETCH_WEATHER_FAILED';
export const FETCH_WEATHER_STARTED = 'FETCH_WEATHER_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_STARTED = 'LOGIN_START';
